-- ============================================================
-- PROYECTO SMILECARE
-- 00_schema_smilecare.sql
--
-- Curso:
-- SC-504 Lenguajes de Base de Datos
--
-- Objetivo:
-- Crear la estructura base de la base de datos SmileCare.
--
-- Este script crea las tablas principales de:
--
-- 1. Seguridad y acceso
-- 2. Pacientes y doctores
-- 3. Agenda y clínica
-- 4. Facturación y pagos
-- 5. Inventario y compras
--
-- IMPORTANTE:
-- Este script elimina primero las tablas SmileCare existentes.
-- No debe ejecutarse sobre una base de datos con información
-- que se quiera conservar.
-- ============================================================


SET DEFINE OFF;
SET SERVEROUTPUT ON;


PROMPT ============================================================
PROMPT INICIANDO CREACION DEL ESQUEMA BASE DE SMILECARE
PROMPT ============================================================


-- ============================================================
-- 1. LIMPIEZA DEL ESQUEMA
-- ============================================================
--
-- Se eliminan únicamente las tablas pertenecientes a SmileCare.
--
-- CASCADE CONSTRAINTS elimina las restricciones dependientes.
-- PURGE evita enviar las tablas a la papelera de Oracle.
--
-- También se incluyen las tablas de auditoría y recuperación
-- agregadas en etapas posteriores del proyecto. De esta manera,
-- la instalación completa puede repetirse desde cero.
-- ============================================================


BEGIN
    FOR t IN (
        SELECT table_name
        FROM user_tables
        WHERE table_name IN (
            'PASSWORD_RESET_TOKENS',
            'AUDITORIA_SISTEMA',
            'HISTORIAL_ACCESOS',
            'AUDITORIA_ACCIONES',

            'COMPROBANTES',
            'PAGOS',
            'DETALLE_FACTURA',
            'FACTURAS',

            'CIRUGIAS',
            'TRATAMIENTOS_CONSULTA',
            'TRATAMIENTOS',

            'MOVIMIENTOS_INVENTARIO',
            'DETALLE_COMPRA',
            'COMPRAS',
            'INVENTARIO_STOCK',
            'INSUMOS',
            'PROVEEDORES',

            'METODOS_PAGO',

            'HISTORIAL_MEDICO',
            'CONSULTAS',
            'CITAS',
            'DISPONIBILIDAD_DOCTORES',
            'HORARIOS_DOCTORES',

            'DOCTORES',
            'ESPECIALIDADES',
            'PACIENTES',

            'USUARIOS',
            'ROL_PERMISOS',
            'PERMISOS',
            'ROLES'
        )
    ) LOOP
        EXECUTE IMMEDIATE (
            'DROP TABLE '
            || t.table_name
            || ' CASCADE CONSTRAINTS PURGE'
        );
    END LOOP;
END;
/


PROMPT Limpieza del esquema completada.


-- ============================================================
-- 2. TABLAS DE SEGURIDAD Y ACCESO
-- ============================================================


-- ------------------------------------------------------------
-- ROLES
--
-- Almacena los roles disponibles en SmileCare.
--
-- Ejemplos finales:
-- ADMIN
-- DOCTOR
-- INVENTARIO
-- RECEPCIONISTA
-- ------------------------------------------------------------


CREATE TABLE roles (
    rol_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    nombre_rol VARCHAR2(50) NOT NULL,

    descripcion VARCHAR2(200),

    estado VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_roles
        PRIMARY KEY (rol_id),

    CONSTRAINT uk_roles_nombre
        UNIQUE (nombre_rol)
);


-- ------------------------------------------------------------
-- PERMISOS
--
-- Registra cada permiso funcional utilizado por el sistema.
--
-- Ejemplos:
-- PACIENTES_VER
-- CAJA_USAR
-- INVENTARIO_GESTIONAR
-- ADMIN_GESTIONAR
-- ------------------------------------------------------------


CREATE TABLE permisos (
    permiso_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    codigo_permiso VARCHAR2(80) NOT NULL,

    descripcion VARCHAR2(200),

    modulo VARCHAR2(50),

    CONSTRAINT pk_permisos
        PRIMARY KEY (permiso_id),

    CONSTRAINT uk_permisos_codigo
        UNIQUE (codigo_permiso)
);


-- ------------------------------------------------------------
-- ROL_PERMISOS
--
-- Tabla intermedia para la relación muchos a muchos entre
-- ROLES y PERMISOS.
-- ------------------------------------------------------------


CREATE TABLE rol_permisos (
    rol_id NUMBER(10) NOT NULL,

    permiso_id NUMBER(10) NOT NULL,

    CONSTRAINT pk_rol_permisos
        PRIMARY KEY (
            rol_id,
            permiso_id
        ),

    CONSTRAINT fk_rolperm_roles
        FOREIGN KEY (rol_id)
        REFERENCES roles (rol_id),

    CONSTRAINT fk_rolperm_permisos
        FOREIGN KEY (permiso_id)
        REFERENCES permisos (permiso_id)
);


-- ------------------------------------------------------------
-- USUARIOS
--
-- Almacena las cuentas de acceso al sistema.
--
-- PASSWORD_HASH contiene la contraseña protegida.
--
-- CORREO se utiliza para el proceso seguro de recuperación
-- de contraseña.
-- ------------------------------------------------------------


CREATE TABLE usuarios (
    usuario_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    rol_id NUMBER(10) NOT NULL,

    nombre_usuario VARCHAR2(50) NOT NULL,

    correo VARCHAR2(150),

    password_hash VARCHAR2(255) NOT NULL,

    estado VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_usuarios
        PRIMARY KEY (usuario_id),

    CONSTRAINT uk_usuarios_nombre
        UNIQUE (nombre_usuario),

    CONSTRAINT fk_usuarios_roles
        FOREIGN KEY (rol_id)
        REFERENCES roles (rol_id)
);


-- ============================================================
-- 3. TABLAS DE PACIENTES Y DOCTORES
-- ============================================================


-- ------------------------------------------------------------
-- PACIENTES
--
-- Almacena la información personal de cada paciente.
--
-- USUARIO_ID es opcional porque un paciente puede existir
-- en la clínica sin tener una cuenta para iniciar sesión.
-- ------------------------------------------------------------


CREATE TABLE pacientes (
    paciente_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    usuario_id NUMBER(10),

    nombre VARCHAR2(100) NOT NULL,

    apellido VARCHAR2(100) NOT NULL,

    telefono VARCHAR2(20),

    correo VARCHAR2(150),

    direccion VARCHAR2(200),

    fecha_nacimiento DATE,

    CONSTRAINT pk_pacientes
        PRIMARY KEY (paciente_id),

    CONSTRAINT uk_pacientes_usuario
        UNIQUE (usuario_id),

    CONSTRAINT fk_pacientes_usuarios
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios (usuario_id)
);


-- ------------------------------------------------------------
-- ESPECIALIDADES
--
-- Almacena las especialidades odontológicas disponibles.
-- ------------------------------------------------------------


CREATE TABLE especialidades (
    especialidad_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    nombre VARCHAR2(100) NOT NULL,

    descripcion VARCHAR2(200),

    CONSTRAINT pk_especialidades
        PRIMARY KEY (especialidad_id),

    CONSTRAINT uk_especialidades_nombre
        UNIQUE (nombre)
);


-- ------------------------------------------------------------
-- DOCTORES
--
-- Registra los odontólogos y su especialidad.
--
-- USUARIO_ID es opcional para permitir doctores registrados
-- que todavía no tengan una cuenta de acceso.
-- ------------------------------------------------------------


CREATE TABLE doctores (
    doctor_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    usuario_id NUMBER(10),

    especialidad_id NUMBER(10) NOT NULL,

    nombre VARCHAR2(100) NOT NULL,

    apellido VARCHAR2(100) NOT NULL,

    telefono VARCHAR2(20),

    correo VARCHAR2(150),

    CONSTRAINT pk_doctores
        PRIMARY KEY (doctor_id),

    CONSTRAINT fk_doctores_usuarios
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios (usuario_id),

    CONSTRAINT fk_doctores_especialidades
        FOREIGN KEY (especialidad_id)
        REFERENCES especialidades (
            especialidad_id
        )
);


-- ============================================================
-- 4. TABLAS DE AGENDA Y CLINICA
-- ============================================================


-- ------------------------------------------------------------
-- CITAS
--
-- Relaciona un paciente con un doctor en una fecha y hora.
--
-- DURACION_MINUTOS permite controlar el bloque reservado
-- dentro de la agenda médica.
-- ------------------------------------------------------------


CREATE TABLE citas (
    cita_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    paciente_id NUMBER(10) NOT NULL,

    doctor_id NUMBER(10) NOT NULL,

    fecha_hora_inicio TIMESTAMP NOT NULL,

    duracion_minutos NUMBER(3) NOT NULL,

    estado VARCHAR2(20) NOT NULL,

    motivo VARCHAR2(250),

    CONSTRAINT pk_citas
        PRIMARY KEY (cita_id),

    CONSTRAINT fk_citas_pacientes
        FOREIGN KEY (paciente_id)
        REFERENCES pacientes (paciente_id),

    CONSTRAINT fk_citas_doctores
        FOREIGN KEY (doctor_id)
        REFERENCES doctores (doctor_id),

    CONSTRAINT ck_citas_duracion
        CHECK (duracion_minutos > 0)
);


-- ------------------------------------------------------------
-- CONSULTAS
--
-- Registra la atención médica realizada a partir de una cita.
--
-- Cada cita puede tener como máximo una consulta.
-- ------------------------------------------------------------


CREATE TABLE consultas (
    consulta_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    cita_id NUMBER(10) NOT NULL,

    diagnostico VARCHAR2(500),

    observaciones VARCHAR2(500),

    fecha_atencion TIMESTAMP,

    CONSTRAINT pk_consultas
        PRIMARY KEY (consulta_id),

    CONSTRAINT uk_consultas_cita
        UNIQUE (cita_id),

    CONSTRAINT fk_consultas_citas
        FOREIGN KEY (cita_id)
        REFERENCES citas (cita_id)
);


-- ------------------------------------------------------------
-- HISTORIAL_MEDICO
--
-- Almacena los antecedentes generales del paciente.
--
-- No reemplaza a CONSULTAS.
--
-- CONSULTAS:
-- eventos de atención individuales.
--
-- HISTORIAL_MEDICO:
-- antecedentes y condiciones generales.
-- ------------------------------------------------------------


CREATE TABLE historial_medico (
    historial_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    paciente_id NUMBER(10) NOT NULL,

    doctor_id NUMBER(10) NOT NULL,

    alergias VARCHAR2(300),

    enfermedades VARCHAR2(300),

    medicamentos VARCHAR2(300),

    antecedentes_quirurgicos VARCHAR2(300),

    observaciones VARCHAR2(500),

    fecha_registro DATE DEFAULT SYSDATE,

    CONSTRAINT pk_historial_medico
        PRIMARY KEY (historial_id),

    CONSTRAINT fk_historial_pacientes
        FOREIGN KEY (paciente_id)
        REFERENCES pacientes (paciente_id),

    CONSTRAINT fk_historial_doctores
        FOREIGN KEY (doctor_id)
        REFERENCES doctores (doctor_id)
);


-- ------------------------------------------------------------
-- HORARIOS_DOCTORES
--
-- Define los horarios recurrentes de trabajo de cada doctor.
--
-- Ejemplo:
-- LUNES, 08:00, 17:00
-- ------------------------------------------------------------


CREATE TABLE horarios_doctores (
    horario_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    doctor_id NUMBER(10) NOT NULL,

    dia_semana VARCHAR2(15) NOT NULL,

    hora_inicio VARCHAR2(5) NOT NULL,

    hora_fin VARCHAR2(5) NOT NULL,

    estado VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_horarios_doctores
        PRIMARY KEY (horario_id),

    CONSTRAINT fk_horarios_doctores
        FOREIGN KEY (doctor_id)
        REFERENCES doctores (doctor_id)
);


-- ------------------------------------------------------------
-- DISPONIBILIDAD_DOCTORES
--
-- Registra disponibilidad o bloqueos específicos por fecha.
-- ------------------------------------------------------------


CREATE TABLE disponibilidad_doctores (
    disponibilidad_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    doctor_id NUMBER(10) NOT NULL,

    fecha DATE NOT NULL,

    hora_inicio VARCHAR2(5) NOT NULL,

    hora_fin VARCHAR2(5) NOT NULL,

    estado VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_disponibilidad_doctores
        PRIMARY KEY (disponibilidad_id),

    CONSTRAINT fk_disponibilidad_doctores
        FOREIGN KEY (doctor_id)
        REFERENCES doctores (doctor_id)
);


-- ------------------------------------------------------------
-- TRATAMIENTOS
--
-- Catálogo de tratamientos ofrecidos por la clínica.
-- ------------------------------------------------------------


CREATE TABLE tratamientos (
    tratamiento_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    nombre VARCHAR2(100) NOT NULL,

    descripcion VARCHAR2(300),

    costo_base NUMBER(10,2) NOT NULL,

    estado VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_tratamientos
        PRIMARY KEY (tratamiento_id),

    CONSTRAINT ck_tratamientos_costo
        CHECK (costo_base >= 0)
);


-- ------------------------------------------------------------
-- TRATAMIENTOS_CONSULTA
--
-- Relaciona los tratamientos aplicados durante una consulta.
--
-- PRECIO_UNITARIO y SUBTOTAL conservan el valor histórico
-- aplicado al paciente.
-- ------------------------------------------------------------


CREATE TABLE tratamientos_consulta (
    tratamiento_consulta_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    consulta_id NUMBER(10) NOT NULL,

    tratamiento_id NUMBER(10) NOT NULL,

    cantidad NUMBER(5) NOT NULL,

    precio_unitario NUMBER(10,2) NOT NULL,

    subtotal NUMBER(10,2) NOT NULL,

    CONSTRAINT pk_tratamientos_consulta
        PRIMARY KEY (
            tratamiento_consulta_id
        ),

    CONSTRAINT fk_tratconsulta_consultas
        FOREIGN KEY (consulta_id)
        REFERENCES consultas (consulta_id),

    CONSTRAINT fk_tratconsulta_tratamientos
        FOREIGN KEY (tratamiento_id)
        REFERENCES tratamientos (
            tratamiento_id
        ),

    CONSTRAINT ck_tratconsulta_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT ck_tratconsulta_precio
        CHECK (precio_unitario >= 0),

    CONSTRAINT ck_tratconsulta_subtotal
        CHECK (subtotal >= 0)
);


-- ------------------------------------------------------------
-- CIRUGIAS
--
-- Contiene información adicional para procedimientos
-- quirúrgicos asociados a un tratamiento aplicado.
-- ------------------------------------------------------------


CREATE TABLE cirugias (
    cirugia_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    tratamiento_consulta_id NUMBER(10) NOT NULL,

    doctor_id NUMBER(10) NOT NULL,

    fecha_cirugia TIMESTAMP,

    descripcion_quirurgica VARCHAR2(500),

    anestesia VARCHAR2(100),

    observaciones VARCHAR2(500),

    estado VARCHAR2(20),

    CONSTRAINT pk_cirugias
        PRIMARY KEY (cirugia_id),

    CONSTRAINT uk_cirugias_tratconsulta
        UNIQUE (tratamiento_consulta_id),

    CONSTRAINT fk_cirugias_tratconsulta
        FOREIGN KEY (
            tratamiento_consulta_id
        )
        REFERENCES tratamientos_consulta (
            tratamiento_consulta_id
        ),

    CONSTRAINT fk_cirugias_doctores
        FOREIGN KEY (doctor_id)
        REFERENCES doctores (doctor_id)
);


-- ============================================================
-- 5. TABLAS DE FACTURACION Y PAGOS
-- ============================================================


-- ------------------------------------------------------------
-- METODOS_PAGO
--
-- Catálogo de formas de pago aceptadas.
-- ------------------------------------------------------------


CREATE TABLE metodos_pago (
    metodo_pago_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    nombre VARCHAR2(50) NOT NULL,

    descripcion VARCHAR2(200),

    estado VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_metodos_pago
        PRIMARY KEY (metodo_pago_id),

    CONSTRAINT uk_metodos_pago_nombre
        UNIQUE (nombre)
);


-- ------------------------------------------------------------
-- FACTURAS
--
-- Registra el cobro emitido a un paciente.
--
-- CONSULTA_ID es opcional para permitir facturas que no
-- provengan directamente de una consulta.
-- ------------------------------------------------------------


CREATE TABLE facturas (
    factura_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    paciente_id NUMBER(10) NOT NULL,

    consulta_id NUMBER(10),

    numero_factura VARCHAR2(30) NOT NULL,

    fecha_emision DATE
        DEFAULT SYSDATE
        NOT NULL,

    subtotal NUMBER(10,2) NOT NULL,

    impuesto NUMBER(10,2),

    total NUMBER(10,2) NOT NULL,

    estado VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_facturas
        PRIMARY KEY (factura_id),

    CONSTRAINT uk_facturas_numero
        UNIQUE (numero_factura),

    CONSTRAINT uk_facturas_consulta
        UNIQUE (consulta_id),

    CONSTRAINT fk_facturas_pacientes
        FOREIGN KEY (paciente_id)
        REFERENCES pacientes (paciente_id),

    CONSTRAINT fk_facturas_consultas
        FOREIGN KEY (consulta_id)
        REFERENCES consultas (consulta_id),

    CONSTRAINT ck_facturas_subtotal
        CHECK (subtotal >= 0),

    CONSTRAINT ck_facturas_impuesto
        CHECK (impuesto >= 0),

    CONSTRAINT ck_facturas_total
        CHECK (total >= 0)
);


-- ------------------------------------------------------------
-- DETALLE_FACTURA
--
-- Registra cada servicio facturado.
-- ------------------------------------------------------------


CREATE TABLE detalle_factura (
    detalle_factura_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    factura_id NUMBER(10) NOT NULL,

    tratamiento_consulta_id NUMBER(10),

    descripcion VARCHAR2(300) NOT NULL,

    cantidad NUMBER(5) NOT NULL,

    precio_unitario NUMBER(10,2) NOT NULL,

    subtotal NUMBER(10,2) NOT NULL,

    CONSTRAINT pk_detalle_factura
        PRIMARY KEY (detalle_factura_id),

    CONSTRAINT fk_detfact_facturas
        FOREIGN KEY (factura_id)
        REFERENCES facturas (factura_id),

    CONSTRAINT fk_detfact_tratconsulta
        FOREIGN KEY (
            tratamiento_consulta_id
        )
        REFERENCES tratamientos_consulta (
            tratamiento_consulta_id
        ),

    CONSTRAINT ck_detfact_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT ck_detfact_precio
        CHECK (precio_unitario >= 0),

    CONSTRAINT ck_detfact_subtotal
        CHECK (subtotal >= 0)
);


-- ------------------------------------------------------------
-- PAGOS
--
-- Registra los pagos aplicados a las facturas.
-- ------------------------------------------------------------


CREATE TABLE pagos (
    pago_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    factura_id NUMBER(10) NOT NULL,

    metodo_pago_id NUMBER(10) NOT NULL,

    monto NUMBER(10,2) NOT NULL,

    fecha_pago DATE
        DEFAULT SYSDATE
        NOT NULL,

    numero_referencia VARCHAR2(100),

    estado VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_pagos
        PRIMARY KEY (pago_id),

    CONSTRAINT fk_pagos_facturas
        FOREIGN KEY (factura_id)
        REFERENCES facturas (factura_id),

    CONSTRAINT fk_pagos_metodos
        FOREIGN KEY (metodo_pago_id)
        REFERENCES metodos_pago (
            metodo_pago_id
        ),

    CONSTRAINT ck_pagos_monto
        CHECK (monto >= 0)
);


-- ------------------------------------------------------------
-- COMPROBANTES
--
-- Almacena el comprobante generado para un pago.
-- ------------------------------------------------------------


CREATE TABLE comprobantes (
    comprobante_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    pago_id NUMBER(10) NOT NULL,

    numero_comprobante VARCHAR2(50) NOT NULL,

    tipo_comprobante VARCHAR2(50),

    fecha_emision DATE
        DEFAULT SYSDATE
        NOT NULL,

    detalle VARCHAR2(300),

    CONSTRAINT pk_comprobantes
        PRIMARY KEY (comprobante_id),

    CONSTRAINT uk_comprobantes_pago
        UNIQUE (pago_id),

    CONSTRAINT uk_comprobantes_numero
        UNIQUE (numero_comprobante),

    CONSTRAINT fk_comprobantes_pagos
        FOREIGN KEY (pago_id)
        REFERENCES pagos (pago_id)
);


-- ============================================================
-- 6. TABLAS DE INVENTARIO Y COMPRAS
-- ============================================================


-- ------------------------------------------------------------
-- PROVEEDORES
--
-- Almacena los proveedores de insumos de la clínica.
-- ------------------------------------------------------------


CREATE TABLE proveedores (
    proveedor_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    nombre VARCHAR2(100) NOT NULL,

    telefono VARCHAR2(20),

    correo VARCHAR2(150),

    direccion VARCHAR2(200),

    estado VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_proveedores
        PRIMARY KEY (proveedor_id)
);


-- ------------------------------------------------------------
-- INSUMOS
--
-- Catálogo de productos e insumos.
-- ------------------------------------------------------------


CREATE TABLE insumos (
    insumo_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    codigo VARCHAR2(50) NOT NULL,

    nombre VARCHAR2(100) NOT NULL,

    descripcion VARCHAR2(300),

    unidad_medida VARCHAR2(30) NOT NULL,

    estado VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_insumos
        PRIMARY KEY (insumo_id),

    CONSTRAINT uk_insumos_codigo
        UNIQUE (codigo)
);


-- ------------------------------------------------------------
-- INVENTARIO_STOCK
--
-- Mantiene el nivel actual de existencia por insumo.
--
-- Cada insumo puede tener solamente un registro de stock.
-- ------------------------------------------------------------


CREATE TABLE inventario_stock (
    stock_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    insumo_id NUMBER(10) NOT NULL,

    stock_actual NUMBER(10,2) NOT NULL,

    stock_minimo NUMBER(10,2),

    ubicacion VARCHAR2(100),

    CONSTRAINT pk_inventario_stock
        PRIMARY KEY (stock_id),

    CONSTRAINT uk_stock_insumo
        UNIQUE (insumo_id),

    CONSTRAINT fk_stock_insumos
        FOREIGN KEY (insumo_id)
        REFERENCES insumos (insumo_id),

    CONSTRAINT ck_stock_actual
        CHECK (stock_actual >= 0),

    CONSTRAINT ck_stock_minimo
        CHECK (stock_minimo >= 0)
);


-- ------------------------------------------------------------
-- COMPRAS
--
-- Registra una compra realizada a un proveedor.
-- ------------------------------------------------------------


CREATE TABLE compras (
    compra_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    proveedor_id NUMBER(10) NOT NULL,

    usuario_id NUMBER(10) NOT NULL,

    fecha_compra DATE
        DEFAULT SYSDATE
        NOT NULL,

    total NUMBER(10,2) NOT NULL,

    estado VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_compras
        PRIMARY KEY (compra_id),

    CONSTRAINT fk_compras_proveedores
        FOREIGN KEY (proveedor_id)
        REFERENCES proveedores (
            proveedor_id
        ),

    CONSTRAINT fk_compras_usuarios
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios (usuario_id),

    CONSTRAINT ck_compras_total
        CHECK (total >= 0)
);


-- ------------------------------------------------------------
-- DETALLE_COMPRA
--
-- Registra los productos incluidos en una compra.
-- ------------------------------------------------------------


CREATE TABLE detalle_compra (
    detalle_compra_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    compra_id NUMBER(10) NOT NULL,

    insumo_id NUMBER(10) NOT NULL,

    cantidad NUMBER(10,2) NOT NULL,

    costo_unitario NUMBER(10,2) NOT NULL,

    subtotal NUMBER(10,2) NOT NULL,

    CONSTRAINT pk_detalle_compra
        PRIMARY KEY (detalle_compra_id),

    CONSTRAINT fk_detcomp_compras
        FOREIGN KEY (compra_id)
        REFERENCES compras (compra_id),

    CONSTRAINT fk_detcomp_insumos
        FOREIGN KEY (insumo_id)
        REFERENCES insumos (insumo_id),

    CONSTRAINT ck_detcomp_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT ck_detcomp_costo
        CHECK (costo_unitario >= 0),

    CONSTRAINT ck_detcomp_subtotal
        CHECK (subtotal >= 0)
);


-- ------------------------------------------------------------
-- MOVIMIENTOS_INVENTARIO
--
-- Registra entradas, salidas y ajustes de inventario.
--
-- DETALLE_COMPRA_ID:
-- se utiliza para movimientos generados por una compra.
--
-- CONSULTA_ID:
-- permite asociar una salida a una atención clínica.
-- ------------------------------------------------------------


CREATE TABLE movimientos_inventario (
    movimiento_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    insumo_id NUMBER(10) NOT NULL,

    usuario_id NUMBER(10) NOT NULL,

    detalle_compra_id NUMBER(10),

    consulta_id NUMBER(10),

    tipo_movimiento VARCHAR2(20) NOT NULL,

    cantidad NUMBER(10,2) NOT NULL,

    fecha_movimiento DATE
        DEFAULT SYSDATE
        NOT NULL,

    motivo VARCHAR2(250),

    CONSTRAINT pk_movimientos_inventario
        PRIMARY KEY (movimiento_id),

    CONSTRAINT fk_movinv_insumos
        FOREIGN KEY (insumo_id)
        REFERENCES insumos (insumo_id),

    CONSTRAINT fk_movinv_usuarios
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios (usuario_id),

    CONSTRAINT fk_movinv_detcomp
        FOREIGN KEY (detalle_compra_id)
        REFERENCES detalle_compra (
            detalle_compra_id
        ),

    CONSTRAINT fk_movinv_consultas
        FOREIGN KEY (consulta_id)
        REFERENCES consultas (consulta_id),

    CONSTRAINT ck_movinv_tipo
        CHECK (
            tipo_movimiento IN (
                'ENTRADA',
                'SALIDA',
                'AJUSTE'
            )
        ),

    CONSTRAINT ck_movinv_cantidad
        CHECK (cantidad > 0)
);


-- ============================================================
-- 7. INDICES PARA LLAVES FORANEAS Y CONSULTAS FRECUENTES
-- ============================================================
--
-- Oracle no crea automáticamente índices para todas las llaves
-- foráneas.
--
-- Estos índices ayudan al rendimiento de consultas JOIN,
-- búsquedas por relaciones y operaciones de mantenimiento.
-- ============================================================


CREATE INDEX idx_usuarios_rol
    ON usuarios (rol_id);


CREATE INDEX idx_pacientes_usuario
    ON pacientes (usuario_id);


CREATE INDEX idx_doctores_usuario
    ON doctores (usuario_id);


CREATE INDEX idx_doctores_especialidad
    ON doctores (especialidad_id);


CREATE INDEX idx_citas_paciente
    ON citas (paciente_id);


CREATE INDEX idx_citas_doctor
    ON citas (doctor_id);


CREATE INDEX idx_citas_fecha
    ON citas (fecha_hora_inicio);


CREATE INDEX idx_consultas_cita
    ON consultas (cita_id);


CREATE INDEX idx_historial_paciente
    ON historial_medico (paciente_id);


CREATE INDEX idx_historial_doctor
    ON historial_medico (doctor_id);


CREATE INDEX idx_horarios_doctor
    ON horarios_doctores (doctor_id);


CREATE INDEX idx_disponibilidad_doctor
    ON disponibilidad_doctores (doctor_id);


CREATE INDEX idx_tratconsulta_consulta
    ON tratamientos_consulta (consulta_id);


CREATE INDEX idx_tratconsulta_tratamiento
    ON tratamientos_consulta (
        tratamiento_id
    );


CREATE INDEX idx_cirugias_doctor
    ON cirugias (doctor_id);


CREATE INDEX idx_facturas_paciente
    ON facturas (paciente_id);


CREATE INDEX idx_detfact_factura
    ON detalle_factura (factura_id);


CREATE INDEX idx_pagos_factura
    ON pagos (factura_id);


CREATE INDEX idx_stock_insumo
    ON inventario_stock (insumo_id);


CREATE INDEX idx_compras_proveedor
    ON compras (proveedor_id);


CREATE INDEX idx_compras_usuario
    ON compras (usuario_id);


CREATE INDEX idx_detcomp_compra
    ON detalle_compra (compra_id);


CREATE INDEX idx_detcomp_insumo
    ON detalle_compra (insumo_id);


CREATE INDEX idx_movinv_insumo
    ON movimientos_inventario (insumo_id);


CREATE INDEX idx_movinv_usuario
    ON movimientos_inventario (usuario_id);


-- ============================================================
-- 8. CONFIRMACION DE CREACION
-- ============================================================


COMMIT;


PROMPT ============================================================
PROMPT ESQUEMA BASE DE SMILECARE CREADO CORRECTAMENTE
PROMPT ============================================================


SELECT
    COUNT(*) AS tablas_base_creadas
FROM user_tables
WHERE table_name IN (
    'ROLES',
    'PERMISOS',
    'ROL_PERMISOS',
    'USUARIOS',

    'PACIENTES',
    'ESPECIALIDADES',
    'DOCTORES',

    'CITAS',
    'CONSULTAS',
    'HISTORIAL_MEDICO',
    'HORARIOS_DOCTORES',
    'DISPONIBILIDAD_DOCTORES',
    'TRATAMIENTOS',
    'TRATAMIENTOS_CONSULTA',
    'CIRUGIAS',

    'METODOS_PAGO',
    'FACTURAS',
    'DETALLE_FACTURA',
    'PAGOS',
    'COMPROBANTES',

    'PROVEEDORES',
    'INSUMOS',
    'INVENTARIO_STOCK',
    'COMPRAS',
    'DETALLE_COMPRA',
    'MOVIMIENTOS_INVENTARIO'
);


PROMPT Resultado esperado:
PROMPT TABLAS_BASE_CREADAS = 26


PROMPT ============================================================
PROMPT FIN DE 00_schema_smilecare.sql
PROMPT ============================================================