SET SERVEROUTPUT ON;

PROMPT ============================================
PROMPT CREANDO TABLA DE AUDITORIA
PROMPT ============================================

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE auditoria_acciones (
            auditoria_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
            nombre_tabla VARCHAR2(50) NOT NULL,
            accion VARCHAR2(20) NOT NULL,
            valor_llave VARCHAR2(100),
            usuario_bd VARCHAR2(100) NOT NULL,
            fecha_accion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            detalle VARCHAR2(500),
            CONSTRAINT pk_auditoria_acciones PRIMARY KEY (auditoria_id)
        )
    ';

    DBMS_OUTPUT.PUT_LINE('Tabla AUDITORIA_ACCIONES creada correctamente.');

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('La tabla AUDITORIA_ACCIONES ya existe.');
        ELSE
            RAISE;
        END IF;
END;
/

PROMPT ============================================
PROMPT CREANDO TRIGGERS DE INSERT
PROMPT ============================================

CREATE OR REPLACE TRIGGER trg_aud_pacientes_insert
AFTER INSERT ON pacientes
FOR EACH ROW
BEGIN
    INSERT INTO auditoria_acciones (
        nombre_tabla,
        accion,
        valor_llave,
        usuario_bd,
        detalle
    )
    VALUES (
        'PACIENTES',
        'INSERT',
        TO_CHAR(:NEW.paciente_id),
        USER,
        'Se creó el paciente: ' || :NEW.nombre || ' ' || :NEW.apellido
    );
END;
/

CREATE OR REPLACE TRIGGER trg_aud_doctores_insert
AFTER INSERT ON doctores
FOR EACH ROW
BEGIN
    INSERT INTO auditoria_acciones (
        nombre_tabla,
        accion,
        valor_llave,
        usuario_bd,
        detalle
    )
    VALUES (
        'DOCTORES',
        'INSERT',
        TO_CHAR(:NEW.doctor_id),
        USER,
        'Se creó el doctor: ' || :NEW.nombre || ' ' || :NEW.apellido
    );
END;
/

PROMPT ============================================
PROMPT CREANDO TRIGGERS DE UPDATE
PROMPT ============================================

CREATE OR REPLACE TRIGGER trg_aud_citas_update
AFTER UPDATE ON citas
FOR EACH ROW
BEGIN
    INSERT INTO auditoria_acciones (
        nombre_tabla,
        accion,
        valor_llave,
        usuario_bd,
        detalle
    )
    VALUES (
        'CITAS',
        'UPDATE',
        TO_CHAR(:NEW.cita_id),
        USER,
        'Se actualizó la cita. Estado anterior: ' || :OLD.estado ||
        ', estado nuevo: ' || :NEW.estado
    );
END;
/

CREATE OR REPLACE TRIGGER trg_aud_facturas_update
AFTER UPDATE ON facturas
FOR EACH ROW
BEGIN
    INSERT INTO auditoria_acciones (
        nombre_tabla,
        accion,
        valor_llave,
        usuario_bd,
        detalle
    )
    VALUES (
        'FACTURAS',
        'UPDATE',
        TO_CHAR(:NEW.factura_id),
        USER,
        'Se actualizó la factura. Total anterior: ' || TO_CHAR(:OLD.total) ||
        ', total nuevo: ' || TO_CHAR(:NEW.total)
    );
END;
/

PROMPT ============================================
PROMPT CREANDO TRIGGERS DE DELETE
PROMPT ============================================

CREATE OR REPLACE TRIGGER trg_aud_tratamientos_consulta_delete
BEFORE DELETE ON tratamientos_consulta
FOR EACH ROW
BEGIN
    INSERT INTO auditoria_acciones (
        nombre_tabla,
        accion,
        valor_llave,
        usuario_bd,
        detalle
    )
    VALUES (
        'TRATAMIENTOS_CONSULTA',
        'DELETE',
        TO_CHAR(:OLD.tratamiento_consulta_id),
        USER,
        'Se eliminó un tratamiento aplicado a consulta. Consulta ID: ' ||
        TO_CHAR(:OLD.consulta_id)
    );
END;
/

CREATE OR REPLACE TRIGGER trg_aud_movimientos_inventario_delete
BEFORE DELETE ON movimientos_inventario
FOR EACH ROW
BEGIN
    INSERT INTO auditoria_acciones (
        nombre_tabla,
        accion,
        valor_llave,
        usuario_bd,
        detalle
    )
    VALUES (
        'MOVIMIENTOS_INVENTARIO',
        'DELETE',
        TO_CHAR(:OLD.movimiento_id),
        USER,
        'Se eliminó un movimiento de inventario. Tipo: ' ||
        :OLD.tipo_movimiento || ', cantidad: ' || TO_CHAR(:OLD.cantidad)
    );
END;
/

PROMPT ============================================
PROMPT VERIFICANDO TRIGGERS CREADOS
PROMPT ============================================

SELECT
    trigger_name,
    table_name,
    triggering_event,
    status
FROM user_triggers
WHERE trigger_name IN (
    'TRG_AUD_PACIENTES_INSERT',
    'TRG_AUD_DOCTORES_INSERT',
    'TRG_AUD_CITAS_UPDATE',
    'TRG_AUD_FACTURAS_UPDATE',
    'TRG_AUD_TRATAMIENTOS_CONSULTA_DELETE',
    'TRG_AUD_MOVIMIENTOS_INVENTARIO_DELETE'
)
ORDER BY trigger_name;