-- ============================================================
-- PROYECTO SMILECARE
-- 08_seguridad_aplicacion.sql
--
-- Objetivo:
-- Crear las estructuras adicionales utilizadas por:
--
-- 1. Auditoría de la aplicación
-- 2. Historial de accesos
-- 3. Recuperación segura de contraseñas
--
-- Este script complementa:
--
-- AUDITORIA_ACCIONES
--
-- La tabla AUDITORIA_ACCIONES pertenece a la auditoría mediante
-- triggers de Oracle.
--
-- Las tablas creadas aquí pertenecen a la capa de aplicación.
-- ============================================================


SET DEFINE OFF;
SET SERVEROUTPUT ON;


PROMPT ============================================================
PROMPT CREANDO ESTRUCTURAS DE SEGURIDAD DE LA APLICACION
PROMPT ============================================================


-- ============================================================
-- 1. VERIFICAR COLUMNA CORREO EN USUARIOS
-- ============================================================
--
-- El script 00_schema_smilecare.sql ya crea esta columna.
--
-- Este bloque permite que 08_seguridad_aplicacion.sql también
-- pueda ejecutarse sobre una versión anterior del esquema.
-- ============================================================


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_tab_columns
    WHERE table_name = 'USUARIOS'
      AND column_name = 'CORREO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE usuarios
            ADD (
                correo VARCHAR2(150)
            )
        ';

        DBMS_OUTPUT.PUT_LINE(
            'Columna USUARIOS.CORREO agregada.'
        );
    ELSE
        DBMS_OUTPUT.PUT_LINE(
            'La columna USUARIOS.CORREO ya existe.'
        );
    END IF;
END;
/


-- ============================================================
-- 2. INDICE UNICO PARA CORREO
-- ============================================================
--
-- UPPER(correo) evita que se puedan registrar:
--
-- ejemplo@correo.com
--
-- y:
--
-- EJEMPLO@CORREO.COM
--
-- como si fueran correos diferentes.
--
-- Oracle permite múltiples valores NULL dentro de este índice.
-- ============================================================


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_indexes
    WHERE index_name = 'UX_USUARIOS_CORREO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE UNIQUE INDEX ux_usuarios_correo
            ON usuarios (
                UPPER(correo)
            )
        ';

        DBMS_OUTPUT.PUT_LINE(
            'Indice UX_USUARIOS_CORREO creado.'
        );
    ELSE
        DBMS_OUTPUT.PUT_LINE(
            'El indice UX_USUARIOS_CORREO ya existe.'
        );
    END IF;
END;
/


-- ============================================================
-- 3. HISTORIAL_ACCESOS
-- ============================================================
--
-- Registra eventos de autenticación y seguridad.
--
-- Ejemplos:
--
-- LOGIN_SUCCESS
-- LOGIN_FAILED
-- LOGOUT
-- PASSWORD_RESET_REQUESTED
-- PASSWORD_RESET_COMPLETED
--
-- USUARIO_ID puede quedar NULL si:
--
-- - el usuario fue eliminado posteriormente
-- - se intentó acceder con un usuario inexistente
-- ============================================================


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_tables
    WHERE table_name = 'HISTORIAL_ACCESOS';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE historial_accesos (
                acceso_id NUMBER(10)
                    GENERATED BY DEFAULT ON NULL AS IDENTITY,

                usuario_id NUMBER(10),

                nombre_usuario VARCHAR2(50),

                nombre_rol VARCHAR2(50),

                evento VARCHAR2(80) NOT NULL,

                resultado VARCHAR2(20) NOT NULL,

                detalle VARCHAR2(500),

                ip_origen VARCHAR2(100),

                user_agent VARCHAR2(500),

                request_id VARCHAR2(100),

                fecha_evento TIMESTAMP(6)
                    DEFAULT SYSTIMESTAMP
                    NOT NULL,

                CONSTRAINT pk_historial_accesos
                    PRIMARY KEY (acceso_id),

                CONSTRAINT fk_histac_usuarios
                    FOREIGN KEY (usuario_id)
                    REFERENCES usuarios (usuario_id)
                    ON DELETE SET NULL,

                CONSTRAINT ck_histac_resultado
                    CHECK (
                        resultado IN (
                            'EXITOSO',
                            'FALLIDO',
                            'DENEGADO'
                        )
                    )
            )
        ]';

        DBMS_OUTPUT.PUT_LINE(
            'Tabla HISTORIAL_ACCESOS creada.'
        );
    ELSE
        DBMS_OUTPUT.PUT_LINE(
            'La tabla HISTORIAL_ACCESOS ya existe.'
        );
    END IF;
END;
/


-- ============================================================
-- 4. AUDITORIA_SISTEMA
-- ============================================================
--
-- Registra operaciones realizadas desde la aplicación.
--
-- Ejemplos:
--
-- CREAR
-- ACTUALIZAR
-- ELIMINAR
-- RESTAURAR
-- REVERTIR
-- CAMBIAR_ESTADO
--
-- Esta tabla complementa la auditoría mediante triggers.
-- ============================================================


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_tables
    WHERE table_name = 'AUDITORIA_SISTEMA';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE auditoria_sistema (
                auditoria_sistema_id NUMBER(10)
                    GENERATED BY DEFAULT ON NULL AS IDENTITY,

                usuario_id NUMBER(10),

                nombre_usuario VARCHAR2(50),

                nombre_rol VARCHAR2(50),

                modulo VARCHAR2(80),

                entidad VARCHAR2(80),

                accion VARCHAR2(50) NOT NULL,

                metodo_http VARCHAR2(10),

                ruta VARCHAR2(300),

                valor_llave VARCHAR2(100),

                resultado VARCHAR2(20) NOT NULL,

                status_code NUMBER(3),

                detalle VARCHAR2(500),

                ip_origen VARCHAR2(100),

                request_id VARCHAR2(100),

                fecha_accion TIMESTAMP(6)
                    DEFAULT SYSTIMESTAMP
                    NOT NULL,

                CONSTRAINT pk_auditoria_sistema
                    PRIMARY KEY (
                        auditoria_sistema_id
                    ),

                CONSTRAINT fk_audsis_usuarios
                    FOREIGN KEY (usuario_id)
                    REFERENCES usuarios (usuario_id)
                    ON DELETE SET NULL,

                CONSTRAINT ck_audsis_resultado
                    CHECK (
                        resultado IN (
                            'EXITOSO',
                            'FALLIDO',
                            'DENEGADO'
                        )
                    ),

                CONSTRAINT ck_audsis_status
                    CHECK (
                        status_code IS NULL
                        OR (
                            status_code >= 100
                            AND status_code <= 599
                        )
                    )
            )
        ]';

        DBMS_OUTPUT.PUT_LINE(
            'Tabla AUDITORIA_SISTEMA creada.'
        );
    ELSE
        DBMS_OUTPUT.PUT_LINE(
            'La tabla AUDITORIA_SISTEMA ya existe.'
        );
    END IF;
END;
/


-- ============================================================
-- 5. PASSWORD_RESET_TOKENS
-- ============================================================
--
-- Maneja los enlaces temporales para recuperar una contraseña.
--
-- IMPORTANTE:
--
-- TOKEN_HASH contiene únicamente SHA-256(token).
--
-- El token original nunca se guarda en Oracle.
--
-- FECHA_USO:
--
-- NULL
--     El enlace todavía no ha sido utilizado.
--
-- Valor TIMESTAMP
--     El enlace ya fue consumido o invalidado.
-- ============================================================


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_tables
    WHERE table_name = 'PASSWORD_RESET_TOKENS';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE password_reset_tokens (
                reset_token_id NUMBER(10)
                    GENERATED BY DEFAULT ON NULL AS IDENTITY,

                usuario_id NUMBER(10) NOT NULL,

                token_hash VARCHAR2(64) NOT NULL,

                fecha_creacion TIMESTAMP(6)
                    DEFAULT SYSTIMESTAMP
                    NOT NULL,

                fecha_expiracion TIMESTAMP(6) NOT NULL,

                fecha_uso TIMESTAMP(6),

                solicitud_ip VARCHAR2(100),

                request_id VARCHAR2(100),

                CONSTRAINT pk_password_reset_tokens
                    PRIMARY KEY (reset_token_id),

                CONSTRAINT uk_password_reset_token_hash
                    UNIQUE (token_hash),

                CONSTRAINT fk_passreset_usuarios
                    FOREIGN KEY (usuario_id)
                    REFERENCES usuarios (usuario_id)
                    ON DELETE CASCADE,

                CONSTRAINT ck_passreset_fechas
                    CHECK (
                        fecha_expiracion >
                        fecha_creacion
                    )
            )
        ]';

        DBMS_OUTPUT.PUT_LINE(
            'Tabla PASSWORD_RESET_TOKENS creada.'
        );
    ELSE
        DBMS_OUTPUT.PUT_LINE(
            'La tabla PASSWORD_RESET_TOKENS ya existe.'
        );
    END IF;
END;
/


-- ============================================================
-- 6. INDICES DE HISTORIAL_ACCESOS
-- ============================================================


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_indexes
    WHERE index_name = 'IDX_HISTAC_FECHA';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE INDEX idx_histac_fecha
            ON historial_accesos (
                fecha_evento
            )
        ';
    END IF;
END;
/


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_indexes
    WHERE index_name = 'IDX_HISTAC_USUARIO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE INDEX idx_histac_usuario
            ON historial_accesos (
                usuario_id
            )
        ';
    END IF;
END;
/


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_indexes
    WHERE index_name = 'IDX_HISTAC_EVENTO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE INDEX idx_histac_evento
            ON historial_accesos (
                evento
            )
        ';
    END IF;
END;
/


-- ============================================================
-- 7. INDICES DE AUDITORIA_SISTEMA
-- ============================================================


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_indexes
    WHERE index_name = 'IDX_AUDSIS_FECHA';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE INDEX idx_audsis_fecha
            ON auditoria_sistema (
                fecha_accion
            )
        ';
    END IF;
END;
/


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_indexes
    WHERE index_name = 'IDX_AUDSIS_USUARIO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE INDEX idx_audsis_usuario
            ON auditoria_sistema (
                usuario_id
            )
        ';
    END IF;
END;
/


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_indexes
    WHERE index_name = 'IDX_AUDSIS_MODULO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE INDEX idx_audsis_modulo
            ON auditoria_sistema (
                modulo
            )
        ';
    END IF;
END;
/


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_indexes
    WHERE index_name = 'IDX_AUDSIS_ACCION';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE INDEX idx_audsis_accion
            ON auditoria_sistema (
                accion
            )
        ';
    END IF;
END;
/


-- ============================================================
-- 8. INDICES DE PASSWORD_RESET_TOKENS
-- ============================================================


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_indexes
    WHERE index_name = 'IDX_PASSRESET_USUARIO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE INDEX idx_passreset_usuario
            ON password_reset_tokens (
                usuario_id
            )
        ';
    END IF;
END;
/


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_indexes
    WHERE index_name = 'IDX_PASSRESET_EXPIRACION';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE INDEX idx_passreset_expiracion
            ON password_reset_tokens (
                fecha_expiracion
            )
        ';
    END IF;
END;
/


COMMIT;


PROMPT ============================================================
PROMPT VERIFICACION DE ESTRUCTURAS DE SEGURIDAD
PROMPT ============================================================


SELECT
    table_name
FROM user_tables
WHERE table_name IN (
    'HISTORIAL_ACCESOS',
    'AUDITORIA_SISTEMA',
    'PASSWORD_RESET_TOKENS'
)
ORDER BY table_name;


SELECT
    index_name,
    table_name
FROM user_indexes
WHERE index_name IN (
    'UX_USUARIOS_CORREO',
    'IDX_HISTAC_FECHA',
    'IDX_HISTAC_USUARIO',
    'IDX_HISTAC_EVENTO',
    'IDX_AUDSIS_FECHA',
    'IDX_AUDSIS_USUARIO',
    'IDX_AUDSIS_MODULO',
    'IDX_AUDSIS_ACCION',
    'IDX_PASSRESET_USUARIO',
    'IDX_PASSRESET_EXPIRACION'
)
ORDER BY table_name, index_name;


PROMPT ============================================================
PROMPT FIN DE 08_seguridad_aplicacion.sql
PROMPT ============================================================